### ISSUE TITLE
Cross check

### ISSUE THREAD

**Issue by BlindWanderer** [AndersFluur/LinkPlayApi#11]
The product listed here:
https://www.arylic.com/collections/diy-audio/products/up2stream-miniv2-receiver-board

Has an API File:
https://cdn.shopify.com/s/files/1/0072/6899/1049/files/WIFI_AUDIO_HTTP_API.pdf

Which looks like an english version of the French PDF.

**Comment by AndersFluur** [comment]
Thanks! It is dated 2014.07, so it it older than the French version that was translated. Can  be used for reference, though. At a quick glance it seems to have some additional information attached.
