### ISSUE TITLE
[Question] Discover correct IP

### ISSUE THREAD

**Issue by tafelnl** [AndersFluur/LinkPlayApi#13]
What is the best way to discover the correct IP to query?
The docs state

> The IP address of Sonoé iEast can be obtained by looking upnp such as 10.10.10.254 (url assume the following interfaces 10.10.10.254 IP)

But I do not understand what this means exactly? Can someone elaborate on this please?

**Comment by nift4** [comment]
Using UPnP SSDP discovery

**Comment by AndersFluur** [comment]
In most cases your router is set up to allocate ip addresses dynamically. When searching for the linkplay device you can open the configuration page of your router to find the address of all active devices.
